apiVersion: v1
kind: Service
metadata:
  name: coreroutex-service
spec:
  type: NodePort                     # expose to host machine
  selector:
    app: coreroutex
  ports:
    - protocol: TCP
      port: 8080                     # internal port
      targetPort: 8080               # container port
      nodePort: 30080                # host port (you can access via localhost:30080)